// ARCHIVO GENERADO por scripts/generate-routes.mjs — NO EDITAR A MANO.
// Se regenera en `npm run dev` y `npm run build` (hooks predev/prebuild) a partir
// de los page.tsx reales bajo src/app. Fuente de verdad: el filesystem.

/** Rutas públicas en inglés (raíz del sitio). */
export const EN_ROUTES: readonly string[] = [
  "/",
  "/ai-assistant",
  "/analytics-reports",
  "/blog",
  "/blog/2026-state-of-education-led-growth",
  "/blog/edtech-partner-continuing-education-guide",
  "/blog/guia-credenciales-digitales",
  "/blog/how-to-evaluate-digital-credentials-platform",
  "/blog/microcredenciales-nueva-arquitectura-aprendizaje",
  "/blog/que-hace-merahki",
  "/blog/reporte-2026-education-led-growth",
  "/careers",
  "/case-studies",
  "/case-studies/uniandes-sanofi-microbiota",
  "/certification",
  "/continuing-education",
  "/customer-education",
  "/david-gonzalez",
  "/education-led-growth",
  "/events",
  "/flexible-courses",
  "/growth-for-universities",
  "/integrations",
  "/interactive-video",
  "/live-sessions",
  "/marketing-your-courses",
  "/medical-education",
  "/methodology",
  "/mobile-app-builder",
  "/partner-academies",
  "/portafolio-virtualizacion",
  "/privacy-policy",
  "/product-adoption",
  "/reports",
  "/reports/microcredentials-digital-credentials-research",
  "/showroom",
  "/survey-builder",
  "/training-certification",
  "/webinars",
  "/website-builder",
];

/** Rutas que tienen versión en español bajo /es (sin el prefijo /es; "/" = home ES). */
export const ES_ROUTES: readonly string[] = [
  "/",
  "/ai-assistant",
  "/analytics-reports",
  "/blog",
  "/blog/edtech-partner-continuing-education-guide",
  "/blog/guia-credenciales-digitales",
  "/blog/microcredenciales-nueva-arquitectura-aprendizaje",
  "/blog/que-hace-merahki",
  "/blog/reporte-2026-education-led-growth",
  "/case-studies",
  "/case-studies/uniandes-sanofi-microbiota",
  "/certification",
  "/continuing-education",
  "/customer-education",
  "/david-gonzalez",
  "/flexible-courses",
  "/growth-for-universities",
  "/integrations",
  "/interactive-video",
  "/live-sessions",
  "/marketing-your-courses",
  "/medical-education",
  "/methodology",
  "/mobile-app-builder",
  "/partner-academies",
  "/product-adoption",
  "/reports",
  "/reports/microcredentials-digital-credentials-research",
  "/survey-builder",
  "/training-certification",
  "/website-builder",
];
